name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Install Coverlet
      run:  cd TestSpellingBee && dotnet add package coverlet.msbuild
    - name: Restore dependencies
      run: dotnet restore ./SpellingBee/SpellingBee.csproj 
    - name: Build
      run: dotnet build --no-restore ./SpellingBee/SpellingBee.csproj
    - name: Location
      run: ls
    - name: Test
      run: dotnet test ./SpellingBee/SpellingBee.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput='./TestResults/result.cobertura.xml'
    - name: Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./TestResults/result.cobertura.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        

